name: aurasync_ui
description: "AuraSync connects your Android to your PC or Mac for remote control, mirroring and real-time data exchange via USB or local network."

version: 0.1.0

homepage: https://softyes.com.br
repository: https://github.com/ZinChat/zinchat_ui

environment:
  sdk: ^3.8.1
  flutter: ^3.32.1

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1
  dynamic_color: ^1.7.0
  solar_icon_pack: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  very_good_analysis: ^8.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/placeholder.jpg
