name: aurasync_ui
description: "AuraSync connects your Android to your PC or Mac for remote control, mirroring and real-time data exchange via USB or local network."

homepage: https://softyes.com.br
repository: https://github.com/AuraSync/aurasync_ui

version: 0.1.0

environment:
  sdk: ^3.9.2
  flutter: ^3.35.4

dependencies:
  flutter:
    sdk: flutter

  lottie: ^3.3.1
  google_fonts: ^6.2.1
  dynamic_color: ^1.7.0
  solar_icon_pack: ^0.2.1
  aurasync_engine:
    path: ../aurasync_engine

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/placeholder.jpg
    - assets/lottie/radar.json
